name: My Workflow

on: [ push, pull_request ]

jobs:
  print-futurama-quote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          character: bender
        id: futurama
      - run: echo ${{steps.futurama.outputs.quote}}
      - uses: ./
        with:
          character: bender
      - run: echo ${{steps.futurama.outputs.quote}}
