name: My Workflow

on: [ push, pull_request, workflow_dispatch ]

jobs:
  print-futurama-quote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          character: bender
        id: futurama
        env:
          THIS_IS_SECURE: ${{ secrets.THIS_IS_SECURE }}
      - run: echo ${{steps.futurama.outputs.quote}}
      - uses: ./
        with:
          character: leela
          quoteCount: 3
      - run: echo ${{steps.futurama.outputs.quote}}
      - name: print secret
        run: |
          if [ "$THIS_IS_SECURE" == "notreally" ]
          then
            echo "not really secret"
          else
            echo "not what I was expecting"
          fi
        env:
          THIS_IS_SECURE: ${{ secrets.THIS_IS_SECURE }}

